version: '3'
services:
  server:
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile

    container_name: server
    restart: always
    image: edinmv/server_p2_201709311
    ports:
      - '5000:5000' 
  ##app de node  
  frontend:
    #build:
    #  context: ./frontend
    #  dockerfile: Dockerfile
    container_name: frontend
    restart: always
    image: edinmv/frontend_p2_201709311
    ports:
      - '3000:3000'
    depends_on:
      - server
    links:
      - server